#!/usr/bin/env python3
"""agents/*.md 를 Codex custom agent 정의(<name>.toml)로 만든다.

Codex 는 `~/.codex/agents/*.toml` 의 name·description·developer_instructions(+ config 키)를 읽는다.
원본의 `## Codex 병행…` 절(Codex 를 셸로 다시 부르는 병행 검토 절차와 출력 형식의 Codex 소절)은
Codex 안에서 돌면 자기 자신을 부르게 되므로 뺀다. model 은 Claude 모델명이라 넣지 않고(Codex 설정
상속), 원본 tools 에 편집 도구도 Bash 도 없으면 `sandbox_mode = "read-only"` 로 읽기 전용을 옮긴다.

    python3 sync_codex_agents.py --source ~/.claude/agents --out ~/.codex/agents [--dry-run | --check]

생성한 파일은 첫 줄 MARKER 로 구분한다. 표식이 없는 같은 이름 파일·심볼릭 링크는 덮지 않고 충돌로
보고하며(나머지는 쓴다), 표식이 있는데 원본이 사라진 파일은 지운다. python 3.9 에서도 돈다(bootstrap
이 시스템 python3 로 부른다).

종료 코드: 0 = 맞춤(또는 씀), 1 = 충돌이 있거나 --check 에서 바뀔 것이 있음, 2 = 원본을 읽지 못함
(아무것도 쓰지 않는다).
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

MARKER = "# generated by scripts/bootstrap/sync_codex_agents.py"
CODEX_SECTION = "## Codex 병행"
# 빠져야 할 절에만 있는 문자열 — 절 제목이 바뀌어 제거를 빠져나가면 쓰지 않고 멈춘다.
LEFTOVER = ("Codex 병행", "codex --version", "preflight")
CODEX_HEADING = re.compile(r"^#{1,6} .*codex", re.IGNORECASE)
EDIT_TOOLS = {"Edit", "Write", "NotebookEdit", "MultiEdit"}
NAME = re.compile(r"[A-Za-z0-9._-]+")
FENCE = re.compile(r"^(`{3,}|~{3,})")


class SourceError(ValueError):
    pass


def preamble() -> str:
    return (
        "> Codex 안에서 도는 사본이므로 Codex CLI 를 다시 실행해 병행 검토하지 않는다(자기 자신을 부르게 "
        "된다). 도구 이름(Read·Grep·Bash 등)은 Claude Code 기준이니 Codex 의 대응 도구로 읽는다.\n\n"
    )


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """한 줄 `key: value` 만 받는다 — 여러 줄 YAML 값은 이 변환기가 옮기지 못하므로 거부한다."""
    text = text.lstrip("\ufeff").replace("\r\n", "\n")
    if not text.startswith("---\n"):
        raise SourceError("frontmatter 가 없다")
    end = text.find("\n---\n", 3)
    if end < 0:
        raise SourceError("frontmatter 가 닫히지 않았다")
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        key, sep, value = line.partition(":")
        value = value.strip()
        if not sep or not key or key != key.strip() or value in ("", ">", "|", ">-", "|-"):
            raise SourceError(f"한 줄 `key: value` 가 아니다: {line!r}")
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
            value = value[1:-1]
        meta[key] = value
    for key in ("name", "description"):
        if key not in meta:
            raise SourceError(f"`{key}` 가 없다")
    if not NAME.fullmatch(meta["name"]):
        raise SourceError(f"파일 이름으로 쓸 수 없는 name: {meta['name']!r}")
    return meta, text[end + len("\n---\n"):]


class _Fences:
    """CommonMark 식 코드 블록 추적 — 닫는 줄은 여는 문자와 같고 길이가 같거나 길며 info string 이 없다."""

    def __init__(self) -> None:
        self.open: str | None = None

    def step(self, line: str) -> bool:
        """이 줄이 울타리 줄이면 상태를 바꾸고 True."""
        m = FENCE.match(line)
        if not m:
            return False
        run = m.group(1)
        if self.open is None:
            self.open = run
            return True
        if run[0] == self.open[0] and len(run) >= len(self.open) and not line[len(run):].strip():
            self.open = None
            return True
        return False


def strip_codex_sections(body: str) -> str:
    """`## Codex 병행` 으로 시작하는 H2 절을 다음 H1·H2 까지 뺀다.

    코드 블록 안의 `## ` 는 본문 헤딩이 아니라 출력 형식 템플릿이다 — 템플릿 안의 `## Codex 병행`
    소절은 블록 안 다음 `## ` 줄이나 블록 끝까지만 빼고, 본문 절의 경계는 바꾸지 않는다. 닫히지 않은
    코드 블록은 경계를 알 수 없어 거부한다.
    """
    out: list[str] = []
    skip = fence_skip = False
    fences = _Fences()
    for line in body.splitlines(keepends=True):
        if fences.step(line):
            if fences.open is None:
                fence_skip = False
        elif fences.open is not None:
            if line.startswith("## "):
                fence_skip = line.startswith(CODEX_SECTION)
        elif line.startswith(("# ", "## ")):
            skip = line.startswith(CODEX_SECTION)
        if not skip and not fence_skip:
            out.append(line)
    if fences.open is not None:
        raise SourceError("닫히지 않은 코드 블록이 있다")
    return "".join(out)


def _check_leftover(instructions: str) -> None:
    """본문 헤딩과 코드 블록 안 템플릿 소절(`## `) 중 codex 가 든 것이 남으면 제거가 샌 것이다."""
    left = [s for s in LEFTOVER if s in instructions]
    fences = _Fences()
    for line in instructions.splitlines():
        if fences.step(line):
            continue
        if (fences.open is None or line.startswith("## ")) and CODEX_HEADING.match(line):
            left.append(line)
    if left:
        raise SourceError(f"Codex 절을 다 빼지 못했다(제목이 바뀌었나): {left}")


def _escape(text: str, multiline: bool) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\n" if multiline else "\\n")
        elif ch == "\t":
            out.append("\t" if multiline else "\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return "".join(out)


def render(source_name: str, meta: dict[str, str], body: str) -> str:
    instructions = preamble() + strip_codex_sections(body).lstrip("\n")
    _check_leftover(instructions)
    lines = [
        f"{MARKER} from agents/{source_name} — 직접 고치지 말고 원본을 고쳐 다시 생성한다",
        f'name = "{_escape(meta["name"], False)}"',
        f'description = "{_escape(meta["description"], False)}"',
    ]
    tools = {t.strip() for t in meta.get("tools", "").split(",") if t.strip()}
    # Bash 가 있으면 원본도 파일을 쓸 수 있다(테스트 실행 등) — 편집 도구도 셸도 없을 때만 읽기 전용.
    if tools and not tools & (EDIT_TOOLS | {"Bash"}):
        lines.append('sandbox_mode = "read-only"')
    # basic string 만 쓴다 — literal('''…''')은 본문에 ''' 가 오면 깨진다.
    lines.append(f'developer_instructions = """\n{_escape(instructions, True)}"""')
    return "\n".join(lines) + "\n"


def _generated(path: Path) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    with path.open(encoding="utf-8", errors="replace") as f:
        return f.readline().startswith(MARKER)


def _same_file(a: Path, b: Path) -> bool:
    try:
        return os.path.samefile(a, b)
    except OSError:
        return False


def _apply(rendered: dict[Path, str], out_dir: Path, write: bool, check: bool) -> int:
    pending = conflicts = 0
    for target, text in rendered.items():
        if target.is_symlink() or (target.exists() and not _generated(target)):
            print(f"conflict {target} — 생성 표식이 없는 파일(또는 링크)이라 덮지 않는다", file=sys.stderr)
            conflicts += 1
            continue
        if target.is_file() and target.read_text(encoding="utf-8") == text:
            print(f"unchanged {target}")
            continue
        pending += 1
        print(f"{'updated' if write else 'would update'} {target}")
        if write:
            out_dir.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
    # 대소문자를 구분하지 않는 FS 에서는 X.toml 과 x.toml 이 같은 파일이다 — 경로가 아니라 파일로 비교한다.
    orphans = [
        p for p in sorted(out_dir.glob("*.toml"))
        if p not in rendered and _generated(p) and not any(_same_file(p, t) for t in rendered)
    ]
    for path in orphans:
        pending += 1
        print(f"{'removed' if write else 'would remove'} {path} — 원본이 없다")
        if write:
            path.unlink()
    if conflicts:
        print("충돌 파일은 agents 폴더 밖으로 옮긴 뒤 다시 실행한다(scripts/bootstrap/README.md 'Codex 연결 충돌').", file=sys.stderr)
        return 1
    return 1 if check and pending else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="agents/*.md → Codex agent 정의(toml)")
    parser.add_argument("--source", required=True, help="agents/*.md 가 있는 디렉토리")
    parser.add_argument("--out", required=True, help="toml 을 쓸 디렉토리(예: ~/.codex/agents)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true", help="바뀔 것만 보여 주고 쓰지 않는다")
    mode.add_argument("--check", action="store_true", help="쓰지 않고, 바뀔 것이 있으면 1 로 끝난다")
    args = parser.parse_args(argv)
    write = not (args.dry_run or args.check)

    sources = sorted(Path(args.source).glob("*.md"))
    if not sources:
        print(f"원본 없음: {args.source}/*.md", file=sys.stderr)
        return 2
    out_dir = Path(args.out)
    rendered: dict[Path, str] = {}
    for md in sources:
        try:
            meta, body = parse_frontmatter(md.read_text(encoding="utf-8"))
            text = render(md.name, meta, body)
        except (SourceError, UnicodeDecodeError, OSError) as e:
            print(f"{md}: {e}", file=sys.stderr)
            return 2
        target = out_dir / f"{meta['name']}.toml"
        if target in rendered:
            print(f"{md}: name 중복 — {meta['name']}", file=sys.stderr)
            return 2
        rendered[target] = text

    try:
        return _apply(rendered, out_dir, write, args.check)
    except (OSError, UnicodeDecodeError) as e:  # 1 은 충돌·drift 전용이라 읽기·쓰기 실패는 2 로
        print(f"{out_dir}: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
